PYTHON_VERSION := 3.11
VENV  := .venv


TEST_SCRIPT := src/test/test.py



env:
	@command -v uv >/dev/null 2>&1 || { \
		echo "Installing uv..."; \
		curl -LsSf https://astral.sh/uv/install.sh | sh; \
	}
	@echo "Setting up eval environment..."
	@uv venv $(EVAL_VENV) --python $(PYTHON_VERSION) --no-project
	@uv pip install -r requirements.txt --python $(EVAL_VENV)/bin/python
	@echo "Evaluation environment ready."


test:
	@$(TRAIN_VENV)/bin/accelerate launch $(SFT_SCRIPT) --config $(SFT_CONFIG)